services:
  postgres_vagasti:
    image: 'postgres:15.1-alpine'
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - networkA
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  vagasti_backend:
    image: 'spring-vagasti:latest'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: vagasti-backend
    ports:
      - "8081:8080"
      - "5005:5005"
    networks:
      - networkA
    depends_on:
      - postgres_vagasti
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

networks:
  networkA:
    name: networkA